---
- name: Chrome autostart with URL
  hosts: all
  become: yes
  become_user: root
  vars_files:
    - vars.yml

  tasks:

  # https://www.raspberrypi.org/documentation/configuration/config-txt.md
  # TODO: http://unix.stackexchange.com/questions/6220/how-can-i-change-the-language-in-chromium
  # TODO: http://stackoverflow.com/questions/7769061/how-to-add-custom-accept-languages-to-chrome-for-pseudolocalization-testing

  - name: HDMI force hotplug
    lineinfile:
      path: /boot/config.txt
      regex: "hdmi_force_hotplug"
      line: "hdmi_force_hotplug=1"
      state: present
    notify: Reboot

  # disable hdmi drive
  - name: HDMI normal mode
    lineinfile:
      path: /boot/config.txt
      regex: "hdmi_drive"
      line: "#hdmi_drive=2"
      state: present
    notify: Reboot

  - name: HDMI group
    lineinfile:
      path: /boot/config.txt
      regex: "hdmi_group"
      line: "hdmi_group=2"
      state: present
    notify: Reboot

  - name: HDMI mode FullHD
    lineinfile:
      path: /boot/config.txt
      regex: "hdmi_mode"
      line: "hdmi_mode=82"
      state: present
    notify: Reboot

  - name: Install packages
    apt: 
      state: present
      name: "{{ packages }}"
    vars:
      packages:
      - unclutter
      - ttf-mscorefonts-installer
      - vlc
      - xinit
      - openbox
      - hsetroot
      - x11vnc
      - ntp
      - ntpdate

  handlers:

  - name: Reboot
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
