---
- name: Set up kitteh client with target URL
  hosts: all
  become: yes
  become_user: root

  tasks:
  - name: Install packages
    apt:
      state: present
      name: "{{ packages }}"
    vars:
      packages:
      - unclutter
      - ttf-mscorefonts-installer
      - vlc
      - xinit
      - xserver-xorg-video-fbdev
      - xserver-xorg-input-all
      - openbox
      - hsetroot
      - x11vnc
      - chromium-browser
      - pulseaudio
      - cec-utils
      - fonts-open-sans

  - name: Install specific xrdp version on debian 11
    apt:
      state: present
      allow_downgrade: yes
      name: xrdp=0.9.12-1.1
    when: ansible_distribution == 'Debian' and ansible_distribution_version == '11'

  - name: Install specific xrdp version on debian 10
    apt:
      state: present
      name: xrdp
    when: ansible_distribution == 'Debian' and ansible_distribution_version == '10'

  - name: Debian 11 - Hold xrdp since newer versions has a bug
    dpkg_selections:
      name: xrdp
      selection: hold
    when: ansible_distribution == 'Debian' and ansible_distribution_version == '11'

  - name: Ensure we're using the correct ntp server
    lineinfile:
      path: /etc/systemd/timesyncd.conf
      regex: "NTP="
      line: "NTP={{ ntpserver }}"
      state: present
    notify: Activate ntp

  - name: Ensure X starts on login
    lineinfile:
      path: /home/{{ autostart_user }}/.bash_profile
      line: "exec startx"
      state: present
      create: yes

  - name: Ensure x11vnc config dir exists
    file:
      path: /home/{{ autostart_user }}/.x11vnc/
      state: directory
      owner: "{{ autostart_user }}"
      group: "{{ autostart_user }}"

  - name: Ensure x11vnc password is set
    shell: sudo -u {{ autostart_user|quote}}  x11vnc -storepasswd {{ vnc_pass|quote }}  /home/{{ autostart_user|quote }}/.x11vnc/passwd
    args:
      creates: /home/{{ autostart_user }}/.x11vnc/passwd

  - name: Ensure openbox config dir exists
    file:
      path: /home/{{ autostart_user }}/.config/openbox/
      state: directory
      owner: "{{ autostart_user }}"
      group: "{{ autostart_user }}"

  - name: Create openbox autostart configuration
    template:
      src: templates/autostart.sh.j2
      dest: "/home/{{ autostart_user }}/.config/openbox/autostart.sh"

  - name: Copy background image
    copy:
      src: files/background_ntnu.png
      dest: "/home/{{ autostart_user|quote }}/background.png"

  - name: Create reload.html
    template:
      src: templates/reload.html.j2
      dest: "/home/{{ autostart_user }}/reload.html"
    notify: Restart getty

  - name: Create frame.html
    template:
      src: templates/frame.html.j2
      dest: "/home/{{ autostart_user }}/frame.html"
    notify: Restart getty

  - name: Ensure getty service override dir exists
    file:
      path: /etc/systemd/system/getty@tty1.service.d/
      state: directory

  - name: Setup autologin user
    lineinfile:
      path: /etc/systemd/system/getty@tty1.service.d/override.conf
      line: "{{ item.line }}"
      state: present
      create: yes
    with_items:
      - { line: "[Service]" }
      - { line: "ExecStart=" }
      - { line: "ExecStart=-/sbin/agetty --autologin {{ autostart_user }} --noclear %I $TERM" }
    notify: Restart getty

  - name: Setup xrdp
    copy:
      src: files/xrdp.ini
      dest: "/etc/xrdp/xrdp.ini"
    notify: Restart xrdp

  - name: Ensure xrdp user is member of ssl-cert group
    user:
      name: xrdp
      groups: ssl-cert
      append: yes

  - name: Set up cron jobs for switching monitors on and off during the day
    block:
      - name: Switch monitor on
        cron:
          name: "Switch monitor on"
          hour: "{{ power_on_hour }}"
          minute: "{{ power_on_minute }}"
          weekday: "{{ power_weekdays }}"
          user: "{{ autostart_user }}"
          job: "echo on 0 | cec-client -s -d 1 > /dev/null"

      - name: Switch monitor off
        cron:
          name: "Switch monitor off"
          hour: "{{ power_off_hour }}"
          minute: "{{ power_off_minute }}"
          weekday: "{{ power_weekdays }}"
          user: "{{ autostart_user }}"
          job: "echo standby 0 | cec-client -s -d 1 > /dev/null"
    when: use_cron|bool == true

  - name: Remove the nopassword-config for the pi user if it exists
    file:
      path: "/etc/sudoers.d/010_pi-nopasswd"
      state: absent

  handlers:
  - name: Restart getty
    include: tasks/restart_getty.yml

  - name: Restart xrdp
    include: tasks/restart_xrdp.yml

  - name: Activate ntp
    include: tasks/activate_ntp.yml
