---
- name: Set up kitteh client with target URL
  hosts: all
  become: yes
  become_user: root
  vars_files:
    - vars.yml

  tasks:

  # https://www.raspberrypi.org/documentation/configuration/config-txt.md
  # TODO: http://unix.stackexchange.com/questions/6220/how-can-i-change-the-language-in-chromium
  # TODO: http://stackoverflow.com/questions/7769061/how-to-add-custom-accept-languages-to-chrome-for-pseudolocalization-testing

  - name: HDMI force hotplug
    lineinfile:
      path: /boot/config.txt
      regex: "hdmi_force_hotplug"
      line: "hdmi_force_hotplug=1"
      state: present
    notify: Reboot

  # disable hdmi drive
  - name: HDMI normal mode
    lineinfile:
      path: /boot/config.txt
      regex: "hdmi_drive"
      line: "#hdmi_drive=2"
      state: present
    notify: Reboot

  - name: HDMI group
    lineinfile:
      path: /boot/config.txt
      regex: "hdmi_group"
      line: "hdmi_group=2"
      state: present
    notify: Reboot

  - name: HDMI mode FullHD
    lineinfile:
      path: /boot/config.txt
      regex: "hdmi_mode"
      line: "hdmi_mode=82"
      state: present
    notify: Reboot

  - name: Install packages
    apt: 
      state: present
      name: "{{ packages }}"
    vars:
      packages:
      - unclutter
      - ttf-mscorefonts-installer
      - vlc
      - xinit
      - openbox
      - hsetroot
      - x11vnc
      - ntp
      - ntpdate
      - chromium-browser
      - pulseaudio
      - xrdp
  
  - name: Ensure X starts on login
    lineinfile:
      path: /home/{{ autostart_user }}/.bash_profile
      line: "exec startx"
      state: present
      create: yes

  - name: Ensure x11vnc config dir exists
    file:
      path: /home/{{ autostart_user }}/.x11vnc/
      state: directory
      owner: "{{ autostart_user }}"
      group: "{{ autostart_user }}"

  - name: Ensure x11vnc password is set
    shell: sudo -u {{ autostart_user|quote}}  x11vnc -storepasswd {{ autostart_vnc_pass|quote }}  /home/{{ autostart_user|quote }}/.x11vnc/passwd
    args:
      creates: /home/{{ autostart_user }}/.x11vnc/passwd
  
  - name: Ensure openbox config dir exists
    file:
      path: /home/{{ autostart_user }}/.config/openbox/
      state: directory
      owner: "{{ autostart_user }}"
      group: "{{ autostart_user }}"

  - name: Create openbox autostart configuration
    template:
      src: templates/autostart.sh.j2
      dest: "/home/{{ autostart_user }}/.config/openbox/autostart.sh"
    notify: Restart getty

  - name: Copy background image
    copy:
      src: files/background.png
      dest: "/home/{{ autostart_user|quote }}/background.png"

  - name: Create reload.html
    template:
      src: templates/reload.html.j2
      dest: "/home/{{ autostart_user }}/reload.html"

  - name: Ensure getty service override dir exists
    file:
      path: /etc/systemd/system/getty@tty1.service.d/
      state: directory

  - name: Setup autologin user
    lineinfile:
      path: /etc/systemd/system/getty@tty1.service.d/override.conf
      line: "{{ item.line }}"
      state: present
      create: yes
    with_items:
      - { line: "[Service]" }
      - { line: "ExecStart=" }
      - { line: "ExecStart=-/sbin/agetty --autologin {{ autostart_user }} --noclear %I $TERM" }
    notify: Restart getty
  
  - name: Setup xrdp
    copy:
      src: files/xrdp.ini
      dest: "/etc/xrdp/xrdp.ini"
    notify: Restart xrdp

  - name: Ensure xrdp user is member of ssl-cert group
    user:
      name: xrdp
      groups: ssl-cert
      append: yes
        
  - name: Remove the nopassword-config for the pi user if it exists
    file:
      path: "/etc/sudoers.d/010_pi-nopasswd"
      state: absent

  handlers:

  - name: Reboot
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true

  - name: Restart getty
    include: tasks/restart_getty.yml
  
  - name: Restart xrdp
    include: tasks/restart_xrdp.yml